import esbuild from 'esbuild';
import path from 'path';
import { copyFileSync, existsSync } from 'fs';

const prod = process.argv[2] === 'production';

const banner = `/*
 * THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
 * Source: https://github.com/notoriouslab/vault-curate
 */
`;

const PLUGIN_ROOT = path.resolve('.');

// ─────────────────────────────────────────────────────────────────────────────
// Ship onnxruntime-web WASM binary as a sibling file.
// main.js reads it at load time and transfers it to the embedding Web Worker on
// init, so the WASM never lives as a JS literal inside main.js or worker.js.
// ─────────────────────────────────────────────────────────────────────────────
const ortWasmSrc = path.resolve(
  './node_modules/onnxruntime-web/dist/ort-wasm-simd-threaded.wasm',
);
if (!existsSync(ortWasmSrc)) {
  throw new Error(
    `Missing onnxruntime-web WASM at ${ortWasmSrc}. Did npm install onnxruntime-web run?`,
  );
}
copyFileSync(ortWasmSrc, path.join(PLUGIN_ROOT, 'ort-wasm-simd-threaded.wasm'));

// ─────────────────────────────────────────────────────────────────────────────
// Workaround 1: Electron dedicated workers expose process.release.name === "node".
// @huggingface/transformers' env.js then sets IS_NODE_ENV=true in the worker and
// loads the empty onnxruntime-node stub, making `InferenceSession` undefined ->
// model load crashes reading 'create' on undefined.
//
// Patch release.name to "electron-worker" BEFORE transformers' env.js runs
// (banner is first in the worker bundle).
// ─────────────────────────────────────────────────────────────────────────────
const WORKER_NODE_PROCESS_PATCH = `(function(){
  try {
    var s = typeof self !== "undefined" ? self : null;
    var inWorker = s && ["DedicatedWorkerGlobalScope","ServiceWorkerGlobalScope","SharedWorkerGlobalScope"].includes(s.constructor && s.constructor.name);
    var p = typeof process !== "undefined" ? process : null;
    if (inWorker && p && p.release && p.release.name === "node") {
      Object.defineProperty(p.release, "name", { value: "electron-worker", configurable: true, enumerable: true });
    }
  } catch (_e) {}
})();`;

// ─────────────────────────────────────────────────────────────────────────────
// Workaround 2: transformers.node.min.cjs requires `sharp` at module-init time
// but never calls it during text embedding. Without this stub, Electron throws
// "Cannot find module 'sharp'" before _loadModel even starts.
// ─────────────────────────────────────────────────────────────────────────────
const nativeStubPlugin = {
  name: 'native-stub',
  setup(build) {
    const stubs = ['sharp'];
    for (const mod of stubs) {
      build.onResolve({ filter: new RegExp(`^${mod}$`) }, () => ({
        path: mod,
        namespace: 'native-stub',
      }));
    }
    build.onLoad({ filter: /.*/, namespace: 'native-stub' }, (args) => ({
      contents: `// stubbed native module: ${args.path}\nmodule.exports = {};`,
      loader: 'js',
    }));
  },
};

// ─────────────────────────────────────────────────────────────────────────────
// Workaround 3 (main bundle): Electron renderer has IS_NODE_ENV=true so we use
// the node build of transformers, but redirect onnxruntime-node (which is a
// native addon) to the pure-WASM ort build so Obsidian can run it.
// ─────────────────────────────────────────────────────────────────────────────
const transformersAliasesMain = {
  '@huggingface/transformers':
    './node_modules/@huggingface/transformers/dist/transformers.node.min.cjs',
  'onnxruntime-node':
    './node_modules/onnxruntime-web/dist/ort.wasm.bundle.min.mjs',
  'onnxruntime-web/webgpu':
    './node_modules/onnxruntime-web/dist/ort.webgpu.bundle.min.mjs',
};

// ─────────────────────────────────────────────────────────────────────────────
// Step 1: Bundle the Web Worker that owns all ONNX/transformers inference.
// The output is captured by main.ts as a string (via fs read at startup) and
// instantiated via Blob URL at runtime — so the plugin still ships as
// main.js + worker.js + sibling WASM.
// ─────────────────────────────────────────────────────────────────────────────
await esbuild.build({
  entryPoints: ['src/workers/embeddingWorker.ts'],
  bundle: true,
  format: 'iife',
  platform: 'browser',
  target: 'es2020',
  banner: { js: WORKER_NODE_PROCESS_PATCH },
  logLevel: 'info',
  minify: false,
  sourcemap: false,
  loader: { '.wasm': 'binary' },
  alias: {
    // Use transformers.web build in the worker (browser context).
    '@huggingface/transformers':
      './node_modules/@huggingface/transformers/dist/transformers.web.js',
    // Use the WebGPU+WASM superset bundle so `device: 'webgpu'` can register
    // the webgpu backend. The wasm-only bundle (which we used before) returns
    // "[webgpu] backend not found" even when navigator.gpu is available.
    // This bundle still ships wasm backend internally for the fallback path.
    'onnxruntime-web':
      './node_modules/onnxruntime-web/dist/ort.webgpu.bundle.min.mjs',
    'onnxruntime-web/webgpu':
      './node_modules/onnxruntime-web/dist/ort.webgpu.bundle.min.mjs',
  },
  plugins: [nativeStubPlugin],
  outfile: path.join(PLUGIN_ROOT, 'worker.js'),
  define: {
    'process.env.NODE_ENV': JSON.stringify(prod ? 'production' : 'development'),
  },
});

// ─────────────────────────────────────────────────────────────────────────────
// Step 2: main plugin bundle. Loads worker.js + sibling ort WASM at runtime.
// sql.js WASM is inlined via loader '.wasm': 'binary' (smaller ~1MB).
// ─────────────────────────────────────────────────────────────────────────────
const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ['src/main.ts'],
  bundle: true,
  loader: { '.wasm': 'binary' },
  alias: transformersAliasesMain,
  external: ['obsidian', 'electron', '@codemirror/*', '@lezer/*'],
  format: 'cjs',
  platform: 'node',
  target: 'es2020',
  logLevel: 'info',
  sourcemap: prod ? false : 'inline',
  treeShaking: true,
  minify: prod,
  outfile: path.join(PLUGIN_ROOT, 'main.js'),
  plugins: [nativeStubPlugin],
});

if (prod) {
  await context.rebuild();
  await context.dispose();
  process.exit(0);
}

await context.watch();
