import esbuild from 'esbuild';
import path from 'path';
import { copyFileSync, existsSync, readFileSync, unlinkSync } from 'fs';

const prod = process.argv[2] === 'production';

const banner = `/*
 * THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
 * Source: https://github.com/notoriouslab/vault-curate
 */
`;

const PLUGIN_ROOT = path.resolve('.');

// ─────────────────────────────────────────────────────────────────────────────
// Hybrid bundling:
//   - worker.js is inlined into main.js as a string (via @inline/worker magic
//     import) so Obsidian Community store users — who only get main.js +
//     manifest + styles — still have the worker available at runtime.
//   - ort-wasm-simd-threaded.wasm stays a sibling release asset. At runtime
//     the worker points onnxruntime-web's wasmPaths at the GitHub releases
//     asset URL instead of cdn.jsdelivr.net (the ORT default). GitHub is
//     reachable for anyone who could install the plugin in the first place;
//     jsdelivr is intermittently blocked in China — this avoids both that
//     ban and a >5MB main.js (Obsidian Sync Standard limit).
// ─────────────────────────────────────────────────────────────────────────────
const ortWasmSrc = path.resolve(
  './node_modules/onnxruntime-web/dist/ort-wasm-simd-threaded.wasm',
);
if (!existsSync(ortWasmSrc)) {
  throw new Error(
    `Missing onnxruntime-web WASM at ${ortWasmSrc}. Did npm install onnxruntime-web run?`,
  );
}
// Copy WASMs to plugin root so release.yml can attach them as release assets.
// (Neither is auto-downloaded by Obsidian Community store, but the worker and
// the sql.js runtime fetch them at runtime from the release URL.)
copyFileSync(ortWasmSrc, path.join(PLUGIN_ROOT, 'ort-wasm-simd-threaded.wasm'));

const sqlJsWasmSrc = path.resolve('./node_modules/sql.js/dist/sql-wasm.wasm');
if (!existsSync(sqlJsWasmSrc)) {
  throw new Error(`Missing sql.js WASM at ${sqlJsWasmSrc}.`);
}
copyFileSync(sqlJsWasmSrc, path.join(PLUGIN_ROOT, 'sql-wasm.wasm'));

const WORKER_BUNDLE_PATH = path.join(PLUGIN_ROOT, 'worker.js');

const inlineWorkerSourcePlugin = {
  name: 'inline-worker-source',
  setup(build) {
    build.onResolve({ filter: /^@inline\/worker$/ }, () => ({
      path: WORKER_BUNDLE_PATH,
      namespace: 'inline-worker',
    }));
    build.onLoad({ filter: /.*/, namespace: 'inline-worker' }, () => {
      if (!existsSync(WORKER_BUNDLE_PATH)) {
        throw new Error(
          `Worker bundle not built yet at ${WORKER_BUNDLE_PATH}. Step 1 must run before Step 2.`,
        );
      }
      const src = readFileSync(WORKER_BUNDLE_PATH, 'utf-8');
      return {
        contents: `export default ${JSON.stringify(src)};`,
        loader: 'js',
      };
    });
  },
};

// ─────────────────────────────────────────────────────────────────────────────
// Workaround 1: Electron dedicated workers expose process.release.name === "node".
// @huggingface/transformers' env.js then sets IS_NODE_ENV=true in the worker and
// loads the empty onnxruntime-node stub, making `InferenceSession` undefined ->
// model load crashes reading 'create' on undefined.
//
// Patch release.name to "electron-worker" BEFORE transformers' env.js runs
// (banner is first in the worker bundle).
// ─────────────────────────────────────────────────────────────────────────────
const WORKER_NODE_PROCESS_PATCH = `(function(){
  try {
    var s = typeof self !== "undefined" ? self : null;
    var inWorker = s && ["DedicatedWorkerGlobalScope","ServiceWorkerGlobalScope","SharedWorkerGlobalScope"].includes(s.constructor && s.constructor.name);
    var p = typeof process !== "undefined" ? process : null;
    if (inWorker && p && p.release && p.release.name === "node") {
      Object.defineProperty(p.release, "name", { value: "electron-worker", configurable: true, enumerable: true });
    }
  } catch (_e) {}
})();`;

// ─────────────────────────────────────────────────────────────────────────────
// Workaround 2: transformers.node.min.cjs requires `sharp` at module-init time
// but never calls it during text embedding. Without this stub, Electron throws
// "Cannot find module 'sharp'" before _loadModel even starts.
// ─────────────────────────────────────────────────────────────────────────────
const nativeStubPlugin = {
  name: 'native-stub',
  setup(build) {
    const stubs = ['sharp'];
    for (const mod of stubs) {
      build.onResolve({ filter: new RegExp(`^${mod}$`) }, () => ({
        path: mod,
        namespace: 'native-stub',
      }));
    }
    build.onLoad({ filter: /.*/, namespace: 'native-stub' }, (args) => ({
      contents: `// stubbed native module: ${args.path}\nmodule.exports = {};`,
      loader: 'js',
    }));
  },
};

// ─────────────────────────────────────────────────────────────────────────────
// Workaround 4: sql.js Emscripten output references `node:fs` (Node fallback
// read path) and `node:crypto` (Node randomFillSync) in dead-code branches
// gated by `process?.type !== "renderer"`. The branches never execute in
// Obsidian's renderer process, but the syntactic `require("node:*")` strings
// remain in the bundle and trigger the Dashboard's "Direct Filesystem Access"
// warning (and would trigger a similar warning if the ruleset expanded to
// other node: builtins). Aliasing both to an empty stub removes the strings.
// ─────────────────────────────────────────────────────────────────────────────
const stripNodeBuiltinsPlugin = {
  name: 'strip-node-builtins',
  setup(build) {
    build.onResolve({ filter: /^node:(fs|crypto)$/ }, (args) => ({
      path: args.path,
      namespace: 'node-builtin-stub',
    }));
    build.onLoad({ filter: /.*/, namespace: 'node-builtin-stub' }, (args) => ({
      contents: `// ${args.path} is unreachable in Obsidian renderer process; this stub keeps the bundle browser-only.\nmodule.exports = {};`,
      loader: 'js',
    }));
  },
};

// ─────────────────────────────────────────────────────────────────────────────
// Workaround 3 (main bundle): Electron renderer has IS_NODE_ENV=true so we use
// the node build of transformers, but redirect onnxruntime-node (which is a
// native addon) to the pure-WASM ort build so Obsidian can run it.
// ─────────────────────────────────────────────────────────────────────────────
const transformersAliasesMain = {
  '@huggingface/transformers':
    './node_modules/@huggingface/transformers/dist/transformers.node.min.cjs',
  'onnxruntime-node':
    './node_modules/onnxruntime-web/dist/ort.wasm.bundle.min.mjs',
  'onnxruntime-web/webgpu':
    './node_modules/onnxruntime-web/dist/ort.webgpu.bundle.min.mjs',
};

// ─────────────────────────────────────────────────────────────────────────────
// Step 1: Bundle the Web Worker that owns all ONNX/transformers inference.
// The output is captured by main.ts as a string (via fs read at startup) and
// instantiated via Blob URL at runtime — so the plugin still ships as
// main.js + worker.js + sibling WASM.
// ─────────────────────────────────────────────────────────────────────────────
await esbuild.build({
  entryPoints: ['src/workers/embeddingWorker.ts'],
  bundle: true,
  format: 'iife',
  platform: 'browser',
  target: 'es2020',
  banner: { js: WORKER_NODE_PROCESS_PATCH },
  logLevel: 'info',
  minify: false,
  sourcemap: false,
  loader: { '.wasm': 'binary' },
  alias: {
    // Use transformers.web build in the worker (browser context).
    '@huggingface/transformers':
      './node_modules/@huggingface/transformers/dist/transformers.web.js',
    // Use the WebGPU+WASM superset bundle so `device: 'webgpu'` can register
    // the webgpu backend. The wasm-only bundle (which we used before) returns
    // "[webgpu] backend not found" even when navigator.gpu is available.
    // This bundle still ships wasm backend internally for the fallback path.
    'onnxruntime-web':
      './node_modules/onnxruntime-web/dist/ort.webgpu.bundle.min.mjs',
    'onnxruntime-web/webgpu':
      './node_modules/onnxruntime-web/dist/ort.webgpu.bundle.min.mjs',
  },
  // NOTE: stripNodeBuiltinsPlugin is intentionally NOT applied to the worker
  // bundle. Worker runs transformers.js + ONNX runtime, both of which may
  // touch node:crypto during model loading / inference (random seed paths).
  // Stubbing it out breaks Chinese semantic embedding (verified 2026-05-21).
  plugins: [nativeStubPlugin],
  outfile: WORKER_BUNDLE_PATH,
  define: {
    'process.env.NODE_ENV': JSON.stringify(prod ? 'production' : 'development'),
  },
});

// ─────────────────────────────────────────────────────────────────────────────
// Step 2: main plugin bundle. Loads worker.js + sibling ort WASM at runtime.
// sql.js WASM is inlined via loader '.wasm': 'binary' (smaller ~1MB).
// ─────────────────────────────────────────────────────────────────────────────
const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ['src/main.ts'],
  bundle: true,
  loader: { '.wasm': 'binary' },
  alias: transformersAliasesMain,
  external: ['obsidian', 'electron', '@codemirror/*', '@lezer/*'],
  format: 'cjs',
  platform: 'node',
  target: 'es2020',
  logLevel: 'info',
  sourcemap: prod ? false : 'inline',
  treeShaking: true,
  minify: prod,
  outfile: path.join(PLUGIN_ROOT, 'main.js'),
  // stripNodeBuiltinsPlugin removes node:fs / node:crypto require() strings
  // from the bundled sql.js Emscripten output (dead-code path that runs only
  // when process.type !== "renderer"). Resolves Dashboard audit Finding 1
  // (Direct Filesystem Access). Worker bundle does NOT apply this plugin —
  // transformers.js / ONNX may need node:crypto for model load / random seed.
  plugins: [nativeStubPlugin, inlineWorkerSourcePlugin, stripNodeBuiltinsPlugin],
});

if (prod) {
  await context.rebuild();
  await context.dispose();
  // Worker source is now inlined into main.js, so the sibling worker.js
  // intermediate is no longer needed. ort-wasm-simd-threaded.wasm IS kept
  // so release.yml can ship it as a release asset (the worker fetches it
  // at runtime via wasmPaths).
  const workerBundle = path.join(PLUGIN_ROOT, 'worker.js');
  if (existsSync(workerBundle)) unlinkSync(workerBundle);
  process.exit(0);
}

await context.watch();
