import esbuild from 'esbuild';
import path from 'path';
import { existsSync, readFileSync, unlinkSync } from 'fs';

const prod = process.argv[2] === 'production';

const banner = `/*
 * THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
 * Source: https://github.com/notoriouslab/vault-curate
 */
`;

const PLUGIN_ROOT = path.resolve('.');

// ─────────────────────────────────────────────────────────────────────────────
// Self-contained bundling: ort WASM is inlined into worker.js (via binary
// loader on the @inline/ort-wasm magic import), and worker.js is inlined into
// main.js as a string (via text loader on the @inline/worker magic import).
// Result: a single main.js ships everything, so Obsidian Community store
// (which only fetches main.js + manifest + styles) gets a fully working plugin
// without depending on cdn.jsdelivr.net at runtime.
// ─────────────────────────────────────────────────────────────────────────────
const ortWasmSrc = path.resolve(
  './node_modules/onnxruntime-web/dist/ort-wasm-simd-threaded.wasm',
);
if (!existsSync(ortWasmSrc)) {
  throw new Error(
    `Missing onnxruntime-web WASM at ${ortWasmSrc}. Did npm install onnxruntime-web run?`,
  );
}

const inlineOrtWasmPlugin = {
  name: 'inline-ort-wasm',
  setup(build) {
    build.onResolve({ filter: /^@inline\/ort-wasm$/ }, () => ({
      path: ortWasmSrc,
      namespace: 'inline-wasm',
    }));
    build.onLoad({ filter: /.*/, namespace: 'inline-wasm' }, () => ({
      contents: readFileSync(ortWasmSrc),
      loader: 'binary',
    }));
  },
};

const WORKER_BUNDLE_PATH = path.join(PLUGIN_ROOT, 'worker.js');

const inlineWorkerSourcePlugin = {
  name: 'inline-worker-source',
  setup(build) {
    build.onResolve({ filter: /^@inline\/worker$/ }, () => ({
      path: WORKER_BUNDLE_PATH,
      namespace: 'inline-worker',
    }));
    build.onLoad({ filter: /.*/, namespace: 'inline-worker' }, () => {
      if (!existsSync(WORKER_BUNDLE_PATH)) {
        throw new Error(
          `Worker bundle not built yet at ${WORKER_BUNDLE_PATH}. Step 1 must run before Step 2.`,
        );
      }
      const src = readFileSync(WORKER_BUNDLE_PATH, 'utf-8');
      return {
        contents: `export default ${JSON.stringify(src)};`,
        loader: 'js',
      };
    });
  },
};

// ─────────────────────────────────────────────────────────────────────────────
// Workaround 1: Electron dedicated workers expose process.release.name === "node".
// @huggingface/transformers' env.js then sets IS_NODE_ENV=true in the worker and
// loads the empty onnxruntime-node stub, making `InferenceSession` undefined ->
// model load crashes reading 'create' on undefined.
//
// Patch release.name to "electron-worker" BEFORE transformers' env.js runs
// (banner is first in the worker bundle).
// ─────────────────────────────────────────────────────────────────────────────
const WORKER_NODE_PROCESS_PATCH = `(function(){
  try {
    var s = typeof self !== "undefined" ? self : null;
    var inWorker = s && ["DedicatedWorkerGlobalScope","ServiceWorkerGlobalScope","SharedWorkerGlobalScope"].includes(s.constructor && s.constructor.name);
    var p = typeof process !== "undefined" ? process : null;
    if (inWorker && p && p.release && p.release.name === "node") {
      Object.defineProperty(p.release, "name", { value: "electron-worker", configurable: true, enumerable: true });
    }
  } catch (_e) {}
})();`;

// ─────────────────────────────────────────────────────────────────────────────
// Workaround 2: transformers.node.min.cjs requires `sharp` at module-init time
// but never calls it during text embedding. Without this stub, Electron throws
// "Cannot find module 'sharp'" before _loadModel even starts.
// ─────────────────────────────────────────────────────────────────────────────
const nativeStubPlugin = {
  name: 'native-stub',
  setup(build) {
    const stubs = ['sharp'];
    for (const mod of stubs) {
      build.onResolve({ filter: new RegExp(`^${mod}$`) }, () => ({
        path: mod,
        namespace: 'native-stub',
      }));
    }
    build.onLoad({ filter: /.*/, namespace: 'native-stub' }, (args) => ({
      contents: `// stubbed native module: ${args.path}\nmodule.exports = {};`,
      loader: 'js',
    }));
  },
};

// ─────────────────────────────────────────────────────────────────────────────
// Workaround 3 (main bundle): Electron renderer has IS_NODE_ENV=true so we use
// the node build of transformers, but redirect onnxruntime-node (which is a
// native addon) to the pure-WASM ort build so Obsidian can run it.
// ─────────────────────────────────────────────────────────────────────────────
const transformersAliasesMain = {
  '@huggingface/transformers':
    './node_modules/@huggingface/transformers/dist/transformers.node.min.cjs',
  'onnxruntime-node':
    './node_modules/onnxruntime-web/dist/ort.wasm.bundle.min.mjs',
  'onnxruntime-web/webgpu':
    './node_modules/onnxruntime-web/dist/ort.webgpu.bundle.min.mjs',
};

// ─────────────────────────────────────────────────────────────────────────────
// Step 1: Bundle the Web Worker that owns all ONNX/transformers inference.
// The output is captured by main.ts as a string (via fs read at startup) and
// instantiated via Blob URL at runtime — so the plugin still ships as
// main.js + worker.js + sibling WASM.
// ─────────────────────────────────────────────────────────────────────────────
await esbuild.build({
  entryPoints: ['src/workers/embeddingWorker.ts'],
  bundle: true,
  format: 'iife',
  platform: 'browser',
  target: 'es2020',
  banner: { js: WORKER_NODE_PROCESS_PATCH },
  logLevel: 'info',
  minify: false,
  sourcemap: false,
  loader: { '.wasm': 'binary' },
  alias: {
    // Use transformers.web build in the worker (browser context).
    '@huggingface/transformers':
      './node_modules/@huggingface/transformers/dist/transformers.web.js',
    // Use the WebGPU+WASM superset bundle so `device: 'webgpu'` can register
    // the webgpu backend. The wasm-only bundle (which we used before) returns
    // "[webgpu] backend not found" even when navigator.gpu is available.
    // This bundle still ships wasm backend internally for the fallback path.
    'onnxruntime-web':
      './node_modules/onnxruntime-web/dist/ort.webgpu.bundle.min.mjs',
    'onnxruntime-web/webgpu':
      './node_modules/onnxruntime-web/dist/ort.webgpu.bundle.min.mjs',
  },
  plugins: [nativeStubPlugin, inlineOrtWasmPlugin],
  outfile: WORKER_BUNDLE_PATH,
  define: {
    'process.env.NODE_ENV': JSON.stringify(prod ? 'production' : 'development'),
  },
});

// ─────────────────────────────────────────────────────────────────────────────
// Step 2: main plugin bundle. Loads worker.js + sibling ort WASM at runtime.
// sql.js WASM is inlined via loader '.wasm': 'binary' (smaller ~1MB).
// ─────────────────────────────────────────────────────────────────────────────
const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ['src/main.ts'],
  bundle: true,
  loader: { '.wasm': 'binary' },
  alias: transformersAliasesMain,
  external: ['obsidian', 'electron', '@codemirror/*', '@lezer/*'],
  format: 'cjs',
  platform: 'node',
  target: 'es2020',
  logLevel: 'info',
  sourcemap: prod ? false : 'inline',
  treeShaking: true,
  minify: prod,
  outfile: path.join(PLUGIN_ROOT, 'main.js'),
  plugins: [nativeStubPlugin, inlineWorkerSourcePlugin],
});

if (prod) {
  await context.rebuild();
  await context.dispose();
  // Worker source + ort WASM are now inlined into main.js. The sibling files
  // produced during the worker build (worker.js, plus any leftover sibling
  // WASM from older builds) are no longer needed. Delete them so the release
  // ships exactly 3 assets — main.js, manifest.json, styles.css.
  for (const f of ['worker.js', 'ort-wasm-simd-threaded.wasm']) {
    const p = path.join(PLUGIN_ROOT, f);
    if (existsSync(p)) unlinkSync(p);
  }
  process.exit(0);
}

await context.watch();
