#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Generate src/indexer/t2sTable.ts from OpenCC TSCharacters (008 D1).

Char-level Traditional→Simplified table for embedding-input preprocessing.
Rules (design.md 008 D1, G1 C2):
  - TSCharacters.txt lines are "trad\tsimp1 simp2 ..." — take simp1
    (OpenCC's official default candidate).
  - Identity mappings (trad == simp1) are dropped (passthrough is free).
  - TSPhrases is deliberately NOT used (word-level disambiguation skipped;
    impact bounded by pilot-fidelity gate, design D6).
  - Also emits scripts/t2s-ambiguous.txt: every one-to-many char and the
    chosen candidate, for pilot-fidelity divergence triage.

Regenerating this table MUST bump T2S_VERSION in src/indexer/preproc.ts.

Requires: pip install opencc-python-reimplemented (dev machine only —
the generated TS module is committed; CI never runs this).
"""
import os
import opencc

DICT = os.path.join(os.path.dirname(opencc.__file__), "dictionary", "TSCharacters.txt")
REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT_TS = os.path.join(REPO, "src", "indexer", "t2sTable.ts")
OUT_AMB = os.path.join(REPO, "scripts", "t2s-ambiguous.txt")

entries = []
ambiguous = []
with open(DICT, encoding="utf-8") as f:
    for line in f:
        line = line.rstrip("\n")
        if not line or "\t" not in line:
            continue
        trad, simps = line.split("\t", 1)
        candidates = simps.split()
        if not candidates:
            continue
        simp = candidates[0]
        if len(candidates) > 1:
            ambiguous.append(f"{trad}\t{' '.join(candidates)}\t→ {simp}")
        if trad == simp:
            continue
        entries.append((trad, simp))

entries.sort()
pairs = ",".join(f'"{t}":"{s}"' for t, s in entries)
ts = (
    "// AUTO-GENERATED by scripts/gen-t2s-table.py — DO NOT EDIT BY HAND.\n"
    "// Source: OpenCC TSCharacters, char-level, first candidate (008 D1).\n"
    "// Regenerating MUST bump T2S_VERSION in preproc.ts (the upgrade\n"
    "// re-embed scan keys off it).\n"
    f"// Entries: {len(entries)} (identity mappings dropped).\n"
    "export const T2S_TABLE: Readonly<Record<string, string>> = {" + pairs + "};\n"
)
with open(OUT_TS, "w", encoding="utf-8") as f:
    f.write(ts)
with open(OUT_AMB, "w", encoding="utf-8") as f:
    f.write("# 一對多字（TSCharacters）與所選首項 — pilot-fidelity 排查用\n")
    f.write("\n".join(ambiguous) + "\n")

print(f"entries: {len(entries)}, ambiguous: {len(ambiguous)}")
print(f"t2sTable.ts: {os.path.getsize(OUT_TS)} bytes")
